### ISSUE TITLE
Support private key exports

### ISSUE THREAD

**Issue by icy-ux** [sparrowwallet/drongo#17]
As discussed [here](https://github.com/sparrowwallet/sparrow/issues/1208) Drongo [does not support exporting private keys](https://github.com/sparrowwallet/drongo/blob/579c86b1a748e410c51f637cd79cbb701996b7e3/src/main/java/com/sparrowwallet/drongo/OutputDescriptor.java) in output descriptors.

This should be fixed.

**Comment by craigraw** [comment]
Let's track this in one place - closing in favour of https://github.com/sparrowwallet/sparrow/issues/1137.
