### ISSUE TITLE
Drongo tarball for each Sparrow release

### ISSUE THREAD

**Issue by eugenesan** [sparrowwallet/drongo#7]
Since github release of Sparrow includes full source tarball it makes sense to also have a corresponding Drongo tarball in each release.
That way it will be possible to re-build Sparrow without using git or for archival reasons.

**Comment by craigraw** [comment]
> Since github release of Sparrow includes full source tarball it makes sense to also have a corresponding Drongo tarball in each release.

This is automatically provided by Github. Unfortunately, it does not appear possible to include submodules in the release tarballs: https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release.

> That way it will be possible to re-build Sparrow without using git or for archival reasons.

It's unclear to me that this adds much - if Github is no longer available, the source tarballs it hosts won't be available either.

**Comment by eugenesan** [comment]
I wasn't aware github had an easy way to fetch corresponding submodule versions for each release.

submodule snapshot is available on a parent release tree snapshot (for example: https://github.com/sparrowwallet/sparrow/tree/1.6.6) and easily downloadable.

That solve the issue.
Thanks.

**Comment by craigraw** [comment]
True, TIL. Click on the drongo submodule, Code > Download ZIP.
