### ISSUE TITLE
Update Gradle to 7.6 to support Java 19

### ISSUE THREAD

**Issue by wombat6** [sparrowwallet/drongo#9]
See https://github.com/sparrowwallet/sparrow/pull/803 for more information.

Currently building Sparrow with Java 19 fails due to dependency on Drongo, which is still using Gradle 7.5, which doesn't support Java 19.

**Comment by craigraw** [comment]
I'm not sure why this happened to you - the gradle wrapper for drongo is not referenced when building using the sparrow's gradle wrapper. Anyway the drongo wrapper is upgraded now.
